# fly.toml app configuration file generated for fullstackopen-ci-cd on 2023-11-30T18:22:59+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstackopen-ci-cd"
primary_region = "syd"

[build]  

[[services]]
  http_checks = [{ 
    interval = 60000,   # Time in milliseconds between checks
    grace_period = "1s",  # Initial period before starting checks
    method = "get",     # HTTP method, typically "get"
    path = "/health",   # The path of your health check endpoint
    timeout = 5000,     # Time in milliseconds to wait for a response
    protocol = "http"   # or "https" if your service is behind SSL
  }]
  internal_port = 8080
  processes = ["app"]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"