# fly.toml app configuration file generated for fullstackopen-ci-cd on 2023-11-30T18:22:59+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstackopen-ci-cd"
primary_region = "syd"

[build]  

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 60000
    grace_period = "1s"
    method = "get"
    path = "/health"
    timeout = 5000
    protocol = "http"


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

